### ISSUE TITLE
front and teas do not register to a2

### ISSUE THREAD

**Issue by imartinezortiz** [e-ucm/rage-analytics#70]
There is an issue in the docker-compose that avoids front to register into a2.
```
front:
  environment:
    - A2_PORT=tcp://a2:3000
...
teas:
  environment:
    - A2_PORT=tcp://a2:3000

```
to 
```
front:
  environment:
    - A2_PORT=http://a2:3000
...
teas:
  environment:
    - A2_PORT=http://a2:3000
```
Also makes sense too to verify and modify the rest of URL to use the proper protocol.
